### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by minad** [pepijnkokke/unlit#3]

**Comment by wenkokke** [comment]
I noticed you have a `stack.yaml` file, but you've not included it in any of your pull requests. Would it be a good idea to include this?

**Comment by minad** [comment]
You could include one to make it easier for developers using stack. But it also ties you to a fixed LTS or nightly, which is not so good. This means you also have to update it from time to time.

stack.yaml:
~~~ yaml
packages:
- .
resolver: lts-7.13
~~~

In general, I would recommend stack.yaml for applications which have huge dependencies or if the dependencies are pulled from git or the filesystem. Especially if stack is the recommended build tool for the given application which is not necessarily the case here.

To add unlit to stackage, you just have to add two lines to https://github.com/fpco/stackage/blob/master/build-constraints.yaml and then it is automatically pulled in!

**Comment by minad** [comment]
ping @pepijnkokke!

Any update on that? If you want I can also add it to stackage.

**Comment by wenkokke** [comment]
Sorry, I’m currently quite busy, but – sure, go ahead!

**Comment by minad** [comment]
In this PR above I am listed as the stackage maintainer for the package, which is ok according to stackage rules. We can change that afterwards when you have more time or if you prefer to be listed yourself. Maintainer is just the one who is notified if something breaks or before the package is kicked out ;)
