### ISSUE TITLE
New cabal version?

### ISSUE THREAD

**Issue by minad** [pepijnkokke/unlit#7]
Hi, it would be great if you find time to upload a new version of unlit to hackage, which would include adoc support. Thank you!

**Comment by wenkokke** [comment]
It seems to me like the version of `unlit` on Hackage is in sync with the master branch of the repository.

**Comment by minad** [comment]
Hi! No it is not. My last PR concerning adoc support is not included in the 0.4.0.0 hackage package.

**Comment by wenkokke** [comment]
I'll upload a new version as soon as the Hackage admins put me back in "Package uploaders" 😅

**Comment by minad** [comment]
Cool, thank you :)

**Comment by minad** [comment]
@wenkokke ping :)

**Comment by wenkokke** [comment]
Still haven't heard back from Hackage, actually... ^__^"

**Comment by minad** [comment]
Oh ok, maybe someone of the hackage trustees can help out here please? @hvr @phadej @erikd...
